---
name:  wordswithletters
title: Word Games
email: marketing@wordgames.com
address: Noida, India
phone: ''
tagline: wordgames - Smartest website for scrabbler world
description: word games testing theme description
siteurl: https://word-games.netlify.app
favicon: /assets/images/word-games-logo.svg
alternateName: wordgames
baseurl: ''
permalink: /blog/:title
author_name: Harshit Raghav
url: https://word-games.netlify.app
copyright_text: © 2020 Word-Games
facebook_username: https://www.facebook.com/word.findersorg
linkedin_username: https://www.linkedin.com/in/wordfindersorg/
instagram_username: https://www.instagram.com/wordfindersorg/
twitter_username: https://twitter.com/wordfindersorg
paginate: '12'
paginate_path: '/blog/page:num/'
keyboard: "Scrabble,Unscrabbler, Words with letters"
clientId: 762288849553-blsuhbaecksbh4tsi5blkhvp2hq9beo5.apps.googleusercontent.com
MonumetricID: //monu.delivery/site/d/0/6481fa-123-4a2e-8a0a-35fdd10adea3.js
production_google_analytics: 'Your_GA_ID'
development_google_analytics: 'Your_GA_ID'
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
disqus:
  shortname: wordswithletters
hero: product_fixed_image
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
getform_id:
mailchimp:
  user-id:
  list-id:
copyright_text: © 2020 Word-Games
company_url: https://word-games.com
google_site_verificatcomn:
bing_site_verificatcomn:
yandex_site_verificatcomn:
naver_site_verificatcomn:
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:
social:
  type:
  name:
  links:
analytics:
  provider: false
  google:
    tracking_id:
    anonymize_ip:
timezone:
