[build]
  functions = "lambda" 

    
[[redirects]]
  from = "/unscramble-letters"
  to = "https://words-xyz.netlify.app"
  force = true
  status = 200


[[redirects]]
  from = "/unscramble-letters/sitemap.xml"
  to = "https://words-xyz.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/unscramble-letters*"
  to = "https://words-xyz.netlify.app/:splat"
  force = true
  status = 200   

[functions]
  included_files = ["wordnet-db/**"]